# Generated by Django 2.2.6 on 2019-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191104_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='work_finished',
        ),
        migrations.RemoveField(
            model_name='team',
            name='work_started',
        ),
    ]
