# Generated by Django 2.2.6 on 2019-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191113_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='work_finished',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончание работы'),
        ),
    ]
